# Generated by Django 4.2.13 on 2024-05-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
