# Generated by Django 4.2.13 on 2024-06-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
